/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { EditFieldOption } from "./components/edit-field/edit-field-option";
export namespace Components {
    interface EditField {
        "action": string;
        "close": () => Promise<void>;
        "open": () => Promise<void>;
        "options": Array<EditFieldOption>;
        "save": () => Promise<void>;
        "value": string;
    }
}
declare global {
    interface HTMLEditFieldElement extends Components.EditField, HTMLStencilElement {
    }
    var HTMLEditFieldElement: {
        prototype: HTMLEditFieldElement;
        new (): HTMLEditFieldElement;
    };
    interface HTMLElementTagNameMap {
        "edit-field": HTMLEditFieldElement;
    }
}
declare namespace LocalJSX {
    interface EditField {
        "action"?: string;
        "onCancel"?: (event: CustomEvent<any>) => void;
        "onChange"?: (event: CustomEvent<any>) => void;
        "onClose"?: (event: CustomEvent<any>) => void;
        "onOpen"?: (event: CustomEvent<any>) => void;
        "onSubmit"?: (event: CustomEvent<string>) => void;
        "onUpdate"?: (event: CustomEvent<string>) => void;
        "options"?: Array<EditFieldOption>;
        "value"?: string;
    }
    interface IntrinsicElements {
        "edit-field": EditField;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "edit-field": LocalJSX.EditField & JSXBase.HTMLAttributes<HTMLEditFieldElement>;
        }
    }
}
